[package]
name = "ait-frontend"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
futures-util.workspace = true

leptos = { version = "0.8", features = ["csr"] }
leptos_router = { version = "0.8" }
leptos_macro = "0.8"
leptos_dom = "0.8"
reactive_graph = "0.2"
reactive_stores = "0.4"

gloo-net = "0.7"
gloo-storage = "0.4"
gloo-timers = { version = "0.4", features = ["futures"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "Window",
  "Document",
  "MediaQueryList",
  "Element",
  "HtmlElement",
  "Navigator",
  "Clipboard",
  "ReadableStream",
  "ReadableStreamDefaultReader",
  "HtmlScriptElement",
  "AbortController",
  "AbortSignal",
  "ResizeObserver",
  "ResizeObserverEntry",
  "DomTokenList",
] }
console_error_panic_hook = "0.1"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"

[build-dependencies]
serde_json.workspace = true
